// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczL7S0U0aEcRlpcw8YNyvZOFqJPiHhFI',
    appId: '1:469930810206:web:54319421a37443f5dd8dcf',
    messagingSenderId: '469930810206',
    projectId: 'fir-app-ff8a3',
    authDomain: 'fir-app-ff8a3.firebaseapp.com',
    storageBucket: 'fir-app-ff8a3.firebasestorage.app',
    measurementId: 'G-XN12XNMNXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFI2MFc_2nPwXWdnjE7nXBKL-8giGn_A',
    appId: '1:469930810206:android:d12cf8c8ee1db13fdd8dcf',
    messagingSenderId: '469930810206',
    projectId: 'fir-app-ff8a3',
    storageBucket: 'fir-app-ff8a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-t1qPh39eeBk8j6KobsKhjOzbEui1pfE',
    appId: '1:469930810206:ios:8b1ce1f204eed66cdd8dcf',
    messagingSenderId: '469930810206',
    projectId: 'fir-app-ff8a3',
    storageBucket: 'fir-app-ff8a3.firebasestorage.app',
    iosClientId: '469930810206-34ujot9tgmfn1ou1kn8vh9bte9hsse0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseAufgabe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-t1qPh39eeBk8j6KobsKhjOzbEui1pfE',
    appId: '1:469930810206:ios:8b1ce1f204eed66cdd8dcf',
    messagingSenderId: '469930810206',
    projectId: 'fir-app-ff8a3',
    storageBucket: 'fir-app-ff8a3.firebasestorage.app',
    iosClientId: '469930810206-34ujot9tgmfn1ou1kn8vh9bte9hsse0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseAufgabe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBczL7S0U0aEcRlpcw8YNyvZOFqJPiHhFI',
    appId: '1:469930810206:web:31778e3e222fedbedd8dcf',
    messagingSenderId: '469930810206',
    projectId: 'fir-app-ff8a3',
    authDomain: 'fir-app-ff8a3.firebaseapp.com',
    storageBucket: 'fir-app-ff8a3.firebasestorage.app',
    measurementId: 'G-WDJWDVBYJD',
  );

}